---

template:
- changed-files:
  - any-glob-to-any-file: 'templates/**/*'

static:
- changed-files:
  - any-glob-to-any-file: 'static/**/*'

content:
- changed-files:
  - any-glob-to-any-file: 'content/**/*'

style:
- changed-files:
  - any-glob-to-any-file: 'sass/**/*'
  - any-glob-to-any-file: '**/*.css'

javascript:
- changed-files:
  - any-glob-to-any-file: '**/*.js'

ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*'
