###
base_url = "https://halve-z.netlify.app"
title = "Halve-Z Zola theme"
description = "Two-column retro theme for Zola"
default_language = "en"
author = "-k"
#theme = "halve-z"

compile_sass = true
minify_html = false
generate_feed = true
build_search_index = true

taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[search]
include_title = true
include_description = true
include_path = false
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
    { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
]
render_emoji = false
external_links_target_blank = true

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
locale = "en_US"
logo = "fireball.gif"
toc = true
csp = true

[extra.home]
title = "Halve-Z"
subtitle = "Zola theme"
glitch = true
logo = { enabled = true, height = "100", width = "100" }


[extra.images]
home = "https://failsafe.monster/c1tyh4ll.png"
post_list = "https://failsafe.monster/bk-prk.jpg"
default_post = "https://failsafe.monster/bk-prk.jpg"
categories = [
    { name = "media", image = "https://raw.githubusercontent.com/bearcott/8bit-art/master/cities/urban.gif" },
]

[extra.menu]
posts = true
links = [
    { name = "Code", url = "@/pages/projects.md" },
]

[extra.footer]
enabled = true
copyright = true
stack = true

[extra.social]
#email = ""
mastodon = "charlesrocket"
twitter = "charlesrocket"
facebook = "charlesrocket"
github = "charlesrocket"
stackoverflow = "9899362/charlie137"
linkedin = "charlesrocket"
instagram = "charlesrocket"
lastfm = "charlesrocket"
#twitch = "charlesrocket"
reddit = "charlesrocket"
flickr = "charlesrocket"
keybase = "charlesrocket"
xmpp = "charlie137@jabber.calyxinstitute.org"
hackernews = "charlesrocket"
#behance = "charlesrocket"

[extra.comments]
system = ""

[extra.comments.cactus]
site = ""
page_size = 10
guest_posting = true
update_interval = 0

[extra.comments.giscus]
repo = ""
repo_id = "REPO_ID"
category = "Comments"
category_id = "CAT_ID"
mapping = "pathname"
strict = "1"
reactions = "1"
lang = "en"
