name = "halve-z"
description = "Retro two-column theme"
license = "MIT"
homepage = "https://github.com/charlesrocket/halvez"
min_version = "0.18.0"
demo = "https://halve-z.netlify.app/"

[extra]
locale = "en_US"
logo = "fireball.gif"
home_title = "Halve-Z"
home_subtitle = "Zola theme"
home_image = "https://failsafe.monster/c1tyh4ll.png"
home_logo = false
post_list_image = "https://failsafe.monster/bk-prk.jpg"
default_post_image = "https://failsafe.monster/bk-prk.jpg"
csp = false
toc = true

[extra.social]
#email = ""
#mastodon = ""
#twitter = ""
#facebook = ""
#github = ""
#stackoverflow = ""
#linkedin = ""
#instagram = ""
#lastfm = ""
#reddit = ""
#flickr = ""
#keybase = ""
#xmpp = ""
#hackernews = ""
#behance = ""

[extra.menu]
posts = false
links = [
    #{ name = "Code", url = "@/pages/projects.md" },
]

[extra.giscus]
enabled = false
repo = ""
repo_id = ""
category = ""
category_id = ""
mapping = ""
strict = "1"
reactions = "0"
lang = "en"

[author]
name = "-k"
homepage = "https://failsafe.monster/"

[original]
author =  "Taylan Tatlı"
homepage = "https://tatli.me/"
repo = "https://github.com/TaylanTatli/Halve"
