name = "halve-z"
description = "Retro two-column theme"
license = "MIT"
homepage = "https://github.com/charlesrocket/halvez"
min_version = "0.18.0"
demo = "https://halve-z.netlify.app/"

[extra]
locale = "en_US"
logo = "fireball.gif"
footer = true
toc = true
csp = false

[extra.home]
title = "Halve-Z"
subtitle = "Zola theme"
glitch = true
logo = { enabled = false, height = "100", width = "100" }

[extra.images]
home = "https://failsafe.monster/c1tyh4ll.png"
post_list = "https://failsafe.monster/bk-prk.jpg"
default_post = "https://failsafe.monster/bk-prk.jpg"
categories = []

[extra.menu]
posts = false
links = [
    #{ name = "Code", url = "@/pages/projects.md" },
]

[extra.social]
#email = ""
#mastodon = ""
#twitter = ""
#facebook = ""
#github = ""
#stackoverflow = ""
#linkedin = ""
#instagram = ""
#lastfm = ""
#reddit = ""
#twitch = ""
#flickr = ""
#keybase = ""
#xmpp = ""
#hackernews = ""
#behance = ""

[extra.comments]
system = ""

[extra.comments.cactus]
site = ""
page_size = 10
guest_posting = true
update_interval = 0

[extra.comments.giscus]
repo = ""
repo_id = ""
category = ""
category_id = ""
mapping = ""
strict = "1"
reactions = "0"
lang = "en"

[author]
name = "-k"
homepage = "https://failsafe.monster/"

[original]
author =  "Taylan Tatlı"
homepage = "https://tatli.me/"
repo = "https://github.com/TaylanTatli/Halve"
